sudo: required
dist: trusty
language: java
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
jdk:
  - oraclejdk8
node_js:
  - 6
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - nvm install 6.10.3
install:
  - npm install
before_script:
  - npm run build
script:
  - npm test
before_deploy:
- cd dist
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: REQZ39rT1djPOzGdHAZNHNYaMvcMwYD3O397aDMyLpaoNHyLGmLknPVQO3LGnW7MPmjFta2hlskvs6AWjgKClZU+qPfFmZ6f+5Poqel9j9LcGXzHEbaqQ8QlUvEwUz8Sp7ViL7RoveSmMyrGGjXoFUy5H/a6hMqaeY8Aggxns9TevaPfZkwEb5OftrRIhDe5RVKDSlfOnFbX9NDZ3MSYuIfRgsWtA5WApieHgSYuoygGaP0Q6F4NdV/JGaYAnfOcfM4XfjHozJaHCGkvHeWrjw/DziMV/1CSMmSylgvZb7DSlcnWqkV2JWtxEA00awgL7T4vnEptRO5tfQ2eXxfK/C+61gQUCxtJYzBCyz5sTXNReE9akdfzd96efEdPMDNoOtxVQAN9LFKGRTyLIJYgfU8lHYSSD3boWvDPR9tDUxJEYXOjX8wjw9mZSBkWshv4wy8cHNNXi/1Arvq+ey13QcwFcHsTXz289OvnYZeXVMj+XOOs7gjGkf8X8Kn8+4EbcqAaVfuSr75cAX1ZT37IhI0axyqpk+CN5G1Fw+agEbOUFHUkd/EFkIha+IR5HuXT3+uTLO4ATm+kUNboIoU26Ft5HWwg9kRvVediteyzX9qPVB6ZdfOjNueCLF2KqU4R/fKlx0D61SvzCpzO0FXIbz8XsiPF2J3LdpAVsQMTUzA=
  app: tbd-frontend
  on:
    repo: tee-bee-dee/tbd-frontend
